- images/collector.Dockerfile
`shfmt`, `shellcheck` and `hub-comment` are all being installed by the collector CI during run time, adding them to the apollo-ci base image would help us cleanup the collector CI a little.
> Add CI tools that were being installed in collector repo

- .circleci/config.yml
- images/scanner-build.Dockerfile
Based on https://github.com/stackrox/rox-ci-image/blob/master/images/stackrox-build.Dockerfile and https://github.com/stackrox/scanner/blob/2.24.0/build/Dockerfile
Similar to the stackrox repo, we should update the scanner repo to use a build image form here instead of the current one embedded in the repo based on `centos:8`. I considered just reusing the `stackrox-build` image, but I ran into issues using it (something about the `libsnappy` shared library being missing. My guess is that issue is related to the fact the `stackrox-build` image uses CGO? I really don't have a better guess than that).
> ROX-10959: Add scanner-build image

- images/circleci-tools/constants.js
- images/stackrox-test.Dockerfile
We no longer use Anchore in CI, so might as well remove it from the images.
> Remove Anchore references

- images/stackrox-test.Dockerfile
Central DB is using Postgres 14 and the Postgres client in the test image is in version 12 which cannot connect to Postgres 14 server in some situation.
> Add postgres client

- images/collector.Dockerfile
After updating the collector CI image to use centos stream8 as its base, the docker command was no longer available which lead to some CI jobs to fail. This PR installs the same docker components found in the original cimg/go image.
> Add docker to the collector CI image

- .circleci/changes_affect.sh
- .circleci/config.yml
- images/scanner-test.Dockerfile
- images/stackrox-test.Dockerfile
This is to handle the plugin change that will be required at v1.25.
```
W0609 20:41:12.637017   29729 gcp.go:120] WARNING: the gcp auth plugin is deprecated in v1.22+, unavailable in v1.25+; use gcloud instead.
To learn more, consult https://cloud.google.com/blog/products/containers-kubernetes/kubectl-auth-changes-in-gke
```
> Update gcloud auth plugin

- images/stackrox-test.Dockerfile
Earlier versions have an [issue](https://github.com/aws/aws-cli/pull/6476) with v1.24 kubectl.
An openshift/release PR was used to test this image as a build root for stackrox and automation-flavors.
- https://github.com/openshift/release/pull/30842
- Passes EKS test: https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_release/30842/rehearse-30842-pull-ci-stackrox-automation-flavors-gavin-OSCI-onboard-EKS-test-eks/1552360140773003264
- Build output: https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift_release/30842/rehearse-30842-pull-ci-stackrox-automation-flavors-gavin-OSCI-onboard-EKS-test-eks/1552360140773003264/artifacts/test-eks/test/build-log.txt
- Passed most GKE tests but will reach rehearsal job limit.
This change …
> Upgrade AWS CLI

- images/collector.Dockerfile
Remove CircleCI specific elements from the collector CI image.
We no longer support CCI and running as the `circleci` user is causing some issues with the driver builds.
> Remove CCI specific instructions from collector image

- Makefile
- images/scanner-build.Dockerfile
- images/scanner-test.Dockerfile
- images/static-contents-scanner/etc/yum.repos.d/google-cloud-sdk.repo
Rollback Scanner to UBI8.
The original bump to UBI9 was done to onboard a new `rpm` version that now is not necessary since `ubi8/ubi-minimal:8.6` ships rpm 4.14.3 which has SQLite backported.
Local tests using the new build image.
> Downgrade scanner builder to stream8

- images/stackrox-build.Dockerfile
These will already be set in the Go source via `#cgo` pragma directives. Specifying those in a container `ENV` OTOH causes _all_ CGo-enabled binaries to be linked against them, which is not desired.
> Do not set RocksDB library link directives via CGO_LDFLAGS env

- .circleci/config.yml
- images/static-contents/scripts/create_update_pr.sh
The repo is small enough that this change isn't likely to break anything.
Also change the PR creation script to not assume the default branch to be called `master` in the other repos.
> inclusive language: Rename 'master' branch to 'main'

- images/scanner-test.Dockerfile
ps can be useful when figuring out what is going on during test.
```
$ oc rsh e2e-tests-e2e-tests
Defaulting container name to test.
Use 'oc describe pod/e2e-tests-e2e-tests -n ci-op-i52dmpmm' to see all of the containers in this pod.
real-bash-4.4$ ps
real-bash: ps: command not found
```
> Scanner test image: Add ps

- images/stackrox-test.Dockerfile
For parallel bats tests i.e. `bats -j N`. Required for changes in https://github.com/stackrox/infra/pull/740.
> Add GNU parallel

- images/stackrox-test.Dockerfile
Although Java 8 is still have security support and openjdk will support it until 2026 it's not actively supported (ended 7 months ago
(31 Mar 2022)) and new libs use features from Java 11 (e.g. logback). This PR updates java to 17 LTS that will be actively supported until 2029. https://endoflife.date/java
> Update java to 17

- images/stackrox-test.Dockerfile
Fixes stackrox/rox-ci-image#173
Looks like jre 8 is installed by default causing issues when trying to use jdk as wrong java version is used.
```
Could not find tools.jar. Please check that /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.322.b06-11.el8.x86_64/jre contains a valid JDK installation
```
This PR removes java 8 after installation java 17 so 17 will be the default and only java version.
Tested:
```sh
[root@3c5aaa14f708 rox]# java -version
openjdk version "1.8.0_322"
OpenJDK Runtime Environment (build 1.8.0_322-b06)
OpenJDK 64-Bit Server VM (build 25.322-b06, mixed mode)
[root@3c5aaa14f708 rox]# dnf remove -y -q java-1.8.0-openjdk-headless
Removed:
java-1.8.0-openjdk-headless-1:1.8.0.322.b06-11.el8.x86_64                               jna-4.5.1-5.el8.x86_64 …
```
> Remove JRE 8

- images/scanner-test.Dockerfile
- images/stackrox-test.Dockerfile
Hoping a more recent version of `oc` will be able to fetch kube API server audit logs, [unlike the current one](https://github.com/stackrox/stackrox/pull/4377) we use.
The currently used version of `oc` was over 4 years old, so I fully expect some trouble rolling this out, as some functionality might have changed.
Tested by running `make stackrox-build-image stackrox-test-image` locally.
> ROX-14352: Bump oc version.

- README.md
Replace CircleCI with GHA. I could not determine an equivalent badge for Quay, so I just left it out
> update README badge

- images/stackrox-build.Dockerfile
Upgrading to Go 1.20.4 addresses the CVE-2023-24540.
(ignore the branch name, this PR has been repurposed).
> ROX-17052: Update Go from 1.20.3 to 1.20.4

- images/stackrox-test.Dockerfile
While running bats tests locally (version 1.10.0), some scanner tests produced a warning:
```
BW02: Using flags on `run` requires at least BATS_VERSION=1.5.0. Use `bats_require_minimum_version 1.5.0` to fix
```
However, adding the call to `bats_require_minimum_version 1.5.0` requires version of at least `1.7.0`. So instead updating to 1.7.0, I decided to update to the newest available versions of bats core, support, and assert.
> Update Bats to 1.10.0

- images/collector.Dockerfile
- images/scanner-build.Dockerfile
- images/stackrox-build.Dockerfile
Update Go to latest downstream available 1.20 version. 
0.3.59 build image is used in upstream 4.3.
Reason for branching off is to avoid any modifications between 0.3.59..0.3.69 (removal of rocksdb, ...).
> bump go to 1.20.12

- images/stackrox-ui-test.Dockerfile
Upgrades Go to 1.22.5 in the stackrox-ui-test image that was missed in https://github.com/stackrox/rox-ci-image/pull/214
> ROX-25438: Upgrade to Go 1.22.5 in stackrox-ui-test

- images/scanner-build.Dockerfile
- images/stackrox-build.Dockerfile
- images/stackrox-ui-test.Dockerfile
Upgrades Go to version 1.23 for stackrox and scanner.
> ROX-27595: Upgrade Go to 1.23

- images/stackrox-test.Dockerfile
stackrox-test image is used to run go-postgres tests and has PostgreSQL installed for that purposes. Now we come to the point that ACS has to be tested against multiple versions. To support that, produce images with a specified PG version in the form
"stackrox-test-$(TEST_TAG)-pg$(PG_VERSION)". The main image will stay there without any changes, and only a consumer CI pipeline that would like to exercise different versions will pick it up.
> ROX-20769: Add PG flavor to the stackrox-test image
